package cpu

var lookup []Instruction

type Instruction struct {
	OpName   byte
	AMName   byte
	AddrMode func() uint8
	Op       func() uint8
	Cycles   uint8
}

func initLookupFor(cpu *Olc6502) {
	lookup = []Instruction{
		{OpName: OPCODE_BRK, AMName: ADDR_MODE_IMM, Op: cpu.BRK, AddrMode: cpu.IMM, Cycles: 7},
		{OpName: OPCODE_ORA, AMName: ADDR_MODE_IZX, Op: cpu.ORA, AddrMode: cpu.IZX, Cycles: 6},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 8},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.NOP, AddrMode: cpu.IMP, Cycles: 3},
		{OpName: OPCODE_ORA, AMName: ADDR_MODE_ZP0, Op: cpu.ORA, AddrMode: cpu.ZP0, Cycles: 3},
		{OpName: OPCODE_ASL, AMName: ADDR_MODE_ZP0, Op: cpu.ASL, AddrMode: cpu.ZP0, Cycles: 5},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 5},
		{OpName: OPCODE_PHP, AMName: ADDR_MODE_IMP, Op: cpu.PHP, AddrMode: cpu.IMP, Cycles: 3},
		{OpName: OPCODE_ORA, AMName: ADDR_MODE_IMM, Op: cpu.ORA, AddrMode: cpu.IMM, Cycles: 2},
		{OpName: OPCODE_ASL, AMName: ADDR_MODE_IMP, Op: cpu.ASL, AddrMode: cpu.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.NOP, AddrMode: cpu.IMP, Cycles: 4},
		{OpName: OPCODE_ORA, AMName: ADDR_MODE_ABS, Op: cpu.ORA, AddrMode: cpu.ABS, Cycles: 4},
		{OpName: OPCODE_ASL, AMName: ADDR_MODE_ABS, Op: cpu.ASL, AddrMode: cpu.ABS, Cycles: 6},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 6},

		{OpName: OPCODE_BPL, AMName: ADDR_MODE_REL, Op: cpu.BPL, AddrMode: cpu.REL, Cycles: 2},
		{OpName: OPCODE_ORA, AMName: ADDR_MODE_IZY, Op: cpu.ORA, AddrMode: cpu.IZY, Cycles: 5},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 8},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.NOP, AddrMode: cpu.IMP, Cycles: 4},
		{OpName: OPCODE_ORA, AMName: ADDR_MODE_ZPX, Op: cpu.ORA, AddrMode: cpu.ZPX, Cycles: 4},
		{OpName: OPCODE_ASL, AMName: ADDR_MODE_ZPX, Op: cpu.ASL, AddrMode: cpu.ZPX, Cycles: 6},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 6},
		{OpName: OPCODE_CLC, AMName: ADDR_MODE_IMP, Op: cpu.CLC, AddrMode: cpu.IMP, Cycles: 2},
		{OpName: OPCODE_ORA, AMName: ADDR_MODE_ABY, Op: cpu.ORA, AddrMode: cpu.ABY, Cycles: 4},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.NOP, AddrMode: cpu.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 7},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.NOP, AddrMode: cpu.IMP, Cycles: 4},
		{OpName: OPCODE_ORA, AMName: ADDR_MODE_ABX, Op: cpu.ORA, AddrMode: cpu.ABX, Cycles: 4},
		{OpName: OPCODE_ASL, AMName: ADDR_MODE_ABX, Op: cpu.ASL, AddrMode: cpu.ABX, Cycles: 7},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 7},

		{OpName: OPCODE_JSR, AMName: ADDR_MODE_ABS, Op: cpu.JSR, AddrMode: cpu.ABS, Cycles: 6},
		{OpName: OPCODE_AND, AMName: ADDR_MODE_IZX, Op: cpu.AND, AddrMode: cpu.IZX, Cycles: 6},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 8},
		{OpName: OPCODE_BIT, AMName: ADDR_MODE_ZP0, Op: cpu.BIT, AddrMode: cpu.ZP0, Cycles: 3},
		{OpName: OPCODE_AND, AMName: ADDR_MODE_ZP0, Op: cpu.AND, AddrMode: cpu.ZP0, Cycles: 3},
		{OpName: OPCODE_ROL, AMName: ADDR_MODE_ZP0, Op: cpu.ROL, AddrMode: cpu.ZP0, Cycles: 5},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 5},
		{OpName: OPCODE_PLP, AMName: ADDR_MODE_IMP, Op: cpu.PLP, AddrMode: cpu.IMP, Cycles: 4},
		{OpName: OPCODE_AND, AMName: ADDR_MODE_IMM, Op: cpu.AND, AddrMode: cpu.IMM, Cycles: 2},
		{OpName: OPCODE_ROL, AMName: ADDR_MODE_IMP, Op: cpu.ROL, AddrMode: cpu.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 2},
		{OpName: OPCODE_BIT, AMName: ADDR_MODE_ABS, Op: cpu.BIT, AddrMode: cpu.ABS, Cycles: 4},
		{OpName: OPCODE_AND, AMName: ADDR_MODE_ABS, Op: cpu.AND, AddrMode: cpu.ABS, Cycles: 4},
		{OpName: OPCODE_ROL, AMName: ADDR_MODE_ABS, Op: cpu.ROL, AddrMode: cpu.ABS, Cycles: 6},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 6},

		{OpName: OPCODE_BMI, AMName: ADDR_MODE_REL, Op: cpu.BMI, AddrMode: cpu.REL, Cycles: 2},
		{OpName: OPCODE_AND, AMName: ADDR_MODE_IZY, Op: cpu.AND, AddrMode: cpu.IZY, Cycles: 5},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 8},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.NOP, AddrMode: cpu.IMP, Cycles: 4},
		{OpName: OPCODE_AND, AMName: ADDR_MODE_ZPX, Op: cpu.AND, AddrMode: cpu.ZPX, Cycles: 4},
		{OpName: OPCODE_ROL, AMName: ADDR_MODE_ZPX, Op: cpu.ROL, AddrMode: cpu.ZPX, Cycles: 6},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 6},
		{OpName: OPCODE_SEC, AMName: ADDR_MODE_IMP, Op: cpu.SEC, AddrMode: cpu.IMP, Cycles: 2},
		{OpName: OPCODE_AND, AMName: ADDR_MODE_ABY, Op: cpu.AND, AddrMode: cpu.ABY, Cycles: 4},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.NOP, AddrMode: cpu.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 7},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.NOP, AddrMode: cpu.IMP, Cycles: 4},
		{OpName: OPCODE_AND, AMName: ADDR_MODE_ABX, Op: cpu.AND, AddrMode: cpu.ABX, Cycles: 4},
		{OpName: OPCODE_ROL, AMName: ADDR_MODE_ABX, Op: cpu.ROL, AddrMode: cpu.ABX, Cycles: 7},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 7},

		{OpName: OPCODE_RTI, AMName: ADDR_MODE_IMP, Op: cpu.RTI, AddrMode: cpu.IMP, Cycles: 6},
		{OpName: OPCODE_EOR, AMName: ADDR_MODE_IZX, Op: cpu.EOR, AddrMode: cpu.IZX, Cycles: 6},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 8},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.NOP, AddrMode: cpu.IMP, Cycles: 3},
		{OpName: OPCODE_EOR, AMName: ADDR_MODE_ZP0, Op: cpu.EOR, AddrMode: cpu.ZP0, Cycles: 3},
		{OpName: OPCODE_LSR, AMName: ADDR_MODE_ZP0, Op: cpu.LSR, AddrMode: cpu.ZP0, Cycles: 5},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 5},
		{OpName: OPCODE_PHA, AMName: ADDR_MODE_IMP, Op: cpu.PHA, AddrMode: cpu.IMP, Cycles: 3},
		{OpName: OPCODE_EOR, AMName: ADDR_MODE_IMM, Op: cpu.EOR, AddrMode: cpu.IMM, Cycles: 2},
		{OpName: OPCODE_LSR, AMName: ADDR_MODE_IMP, Op: cpu.LSR, AddrMode: cpu.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 2},
		{OpName: OPCODE_JMP, AMName: ADDR_MODE_ABS, Op: cpu.JMP, AddrMode: cpu.ABS, Cycles: 3},
		{OpName: OPCODE_EOR, AMName: ADDR_MODE_ABS, Op: cpu.EOR, AddrMode: cpu.ABS, Cycles: 4},
		{OpName: OPCODE_LSR, AMName: ADDR_MODE_ABS, Op: cpu.LSR, AddrMode: cpu.ABS, Cycles: 6},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 6},

		{OpName: OPCODE_BVC, AMName: ADDR_MODE_REL, Op: cpu.BVC, AddrMode: cpu.REL, Cycles: 2},
		{OpName: OPCODE_EOR, AMName: ADDR_MODE_IZY, Op: cpu.EOR, AddrMode: cpu.IZY, Cycles: 5},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 8},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.NOP, AddrMode: cpu.IMP, Cycles: 4},
		{OpName: OPCODE_EOR, AMName: ADDR_MODE_ZPX, Op: cpu.EOR, AddrMode: cpu.ZPX, Cycles: 4},
		{OpName: OPCODE_LSR, AMName: ADDR_MODE_ZPX, Op: cpu.LSR, AddrMode: cpu.ZPX, Cycles: 6},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 6},
		{OpName: OPCODE_CLI, AMName: ADDR_MODE_IMP, Op: cpu.CLI, AddrMode: cpu.IMP, Cycles: 2},
		{OpName: OPCODE_EOR, AMName: ADDR_MODE_ABY, Op: cpu.EOR, AddrMode: cpu.ABY, Cycles: 4},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.NOP, AddrMode: cpu.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 7},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.NOP, AddrMode: cpu.IMP, Cycles: 4},
		{OpName: OPCODE_EOR, AMName: ADDR_MODE_ABX, Op: cpu.EOR, AddrMode: cpu.ABX, Cycles: 4},
		{OpName: OPCODE_LSR, AMName: ADDR_MODE_ABX, Op: cpu.LSR, AddrMode: cpu.ABX, Cycles: 7},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 7},

		{OpName: OPCODE_RTS, AMName: ADDR_MODE_IMP, Op: cpu.RTS, AddrMode: cpu.IMP, Cycles: 6},
		{OpName: OPCODE_ADC, AMName: ADDR_MODE_IZX, Op: cpu.ADC, AddrMode: cpu.IZX, Cycles: 6},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 8},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.NOP, AddrMode: cpu.IMP, Cycles: 3},
		{OpName: OPCODE_ADC, AMName: ADDR_MODE_ZP0, Op: cpu.ADC, AddrMode: cpu.ZP0, Cycles: 3},
		{OpName: OPCODE_ROR, AMName: ADDR_MODE_ZP0, Op: cpu.ROR, AddrMode: cpu.ZP0, Cycles: 5},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 5},
		{OpName: OPCODE_PLA, AMName: ADDR_MODE_IMP, Op: cpu.PLA, AddrMode: cpu.IMP, Cycles: 4},
		{OpName: OPCODE_ADC, AMName: ADDR_MODE_IMM, Op: cpu.ADC, AddrMode: cpu.IMM, Cycles: 2},
		{OpName: OPCODE_ROR, AMName: ADDR_MODE_IMP, Op: cpu.ROR, AddrMode: cpu.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 2},
		{OpName: OPCODE_JMP, AMName: ADDR_MODE_IND, Op: cpu.JMP, AddrMode: cpu.IND, Cycles: 5},
		{OpName: OPCODE_ADC, AMName: ADDR_MODE_ABS, Op: cpu.ADC, AddrMode: cpu.ABS, Cycles: 4},
		{OpName: OPCODE_ROR, AMName: ADDR_MODE_ABS, Op: cpu.ROR, AddrMode: cpu.ABS, Cycles: 6},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 6},

		{OpName: OPCODE_BVS, AMName: ADDR_MODE_REL, Op: cpu.BVS, AddrMode: cpu.REL, Cycles: 2},
		{OpName: OPCODE_ADC, AMName: ADDR_MODE_IZY, Op: cpu.ADC, AddrMode: cpu.IZY, Cycles: 5},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 8},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.NOP, AddrMode: cpu.IMP, Cycles: 4},
		{OpName: OPCODE_ADC, AMName: ADDR_MODE_ZPX, Op: cpu.ADC, AddrMode: cpu.ZPX, Cycles: 4},
		{OpName: OPCODE_ROR, AMName: ADDR_MODE_ZPX, Op: cpu.ROR, AddrMode: cpu.ZPX, Cycles: 6},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 6},
		{OpName: OPCODE_SEI, AMName: ADDR_MODE_IMP, Op: cpu.SEI, AddrMode: cpu.IMP, Cycles: 2},
		{OpName: OPCODE_ADC, AMName: ADDR_MODE_ABY, Op: cpu.ADC, AddrMode: cpu.ABY, Cycles: 4},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.NOP, AddrMode: cpu.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 7},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.NOP, AddrMode: cpu.IMP, Cycles: 4},
		{OpName: OPCODE_ADC, AMName: ADDR_MODE_ABX, Op: cpu.ADC, AddrMode: cpu.ABX, Cycles: 4},
		{OpName: OPCODE_ROR, AMName: ADDR_MODE_ABX, Op: cpu.ROR, AddrMode: cpu.ABX, Cycles: 7},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 7},

		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.NOP, AddrMode: cpu.IMP, Cycles: 2},
		{OpName: OPCODE_STA, AMName: ADDR_MODE_IZX, Op: cpu.STA, AddrMode: cpu.IZX, Cycles: 6},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.NOP, AddrMode: cpu.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 6},
		{OpName: OPCODE_STY, AMName: ADDR_MODE_ZP0, Op: cpu.STY, AddrMode: cpu.ZP0, Cycles: 3},
		{OpName: OPCODE_STA, AMName: ADDR_MODE_ZP0, Op: cpu.STA, AddrMode: cpu.ZP0, Cycles: 3},
		{OpName: OPCODE_STX, AMName: ADDR_MODE_ZP0, Op: cpu.STX, AddrMode: cpu.ZP0, Cycles: 3},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 3},
		{OpName: OPCODE_DEY, AMName: ADDR_MODE_IMP, Op: cpu.DEY, AddrMode: cpu.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.NOP, AddrMode: cpu.IMP, Cycles: 2},
		{OpName: OPCODE_TXA, AMName: ADDR_MODE_IMP, Op: cpu.TXA, AddrMode: cpu.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 2},
		{OpName: OPCODE_STY, AMName: ADDR_MODE_ABS, Op: cpu.STY, AddrMode: cpu.ABS, Cycles: 4},
		{OpName: OPCODE_STA, AMName: ADDR_MODE_ABS, Op: cpu.STA, AddrMode: cpu.ABS, Cycles: 4},
		{OpName: OPCODE_STX, AMName: ADDR_MODE_ABS, Op: cpu.STX, AddrMode: cpu.ABS, Cycles: 4},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 4},

		{OpName: OPCODE_BCC, AMName: ADDR_MODE_REL, Op: cpu.BCC, AddrMode: cpu.REL, Cycles: 2},
		{OpName: OPCODE_STA, AMName: ADDR_MODE_IZY, Op: cpu.STA, AddrMode: cpu.IZY, Cycles: 6},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 6},
		{OpName: OPCODE_STY, AMName: ADDR_MODE_ZPX, Op: cpu.STY, AddrMode: cpu.ZPX, Cycles: 4},
		{OpName: OPCODE_STA, AMName: ADDR_MODE_ZPX, Op: cpu.STA, AddrMode: cpu.ZPX, Cycles: 4},
		{OpName: OPCODE_STX, AMName: ADDR_MODE_ZPY, Op: cpu.STX, AddrMode: cpu.ZPY, Cycles: 4},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 4},
		{OpName: OPCODE_TYA, AMName: ADDR_MODE_IMP, Op: cpu.TYA, AddrMode: cpu.IMP, Cycles: 2},
		{OpName: OPCODE_STA, AMName: ADDR_MODE_ABY, Op: cpu.STA, AddrMode: cpu.ABY, Cycles: 5},
		{OpName: OPCODE_TXS, AMName: ADDR_MODE_IMP, Op: cpu.TXS, AddrMode: cpu.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 5},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.NOP, AddrMode: cpu.IMP, Cycles: 5},
		{OpName: OPCODE_STA, AMName: ADDR_MODE_ABX, Op: cpu.STA, AddrMode: cpu.ABX, Cycles: 5},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 5},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 5},

		{OpName: OPCODE_LDY, AMName: ADDR_MODE_IMM, Op: cpu.LDY, AddrMode: cpu.IMM, Cycles: 2},
		{OpName: OPCODE_LDA, AMName: ADDR_MODE_IZX, Op: cpu.LDA, AddrMode: cpu.IZX, Cycles: 6},
		{OpName: OPCODE_LDX, AMName: ADDR_MODE_IMM, Op: cpu.LDX, AddrMode: cpu.IMM, Cycles: 2},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 6},
		{OpName: OPCODE_LDY, AMName: ADDR_MODE_ZP0, Op: cpu.LDY, AddrMode: cpu.ZP0, Cycles: 3},
		{OpName: OPCODE_LDA, AMName: ADDR_MODE_ZP0, Op: cpu.LDA, AddrMode: cpu.ZP0, Cycles: 3},
		{OpName: OPCODE_LDX, AMName: ADDR_MODE_ZP0, Op: cpu.LDX, AddrMode: cpu.ZP0, Cycles: 3},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 3},
		{OpName: OPCODE_TAY, AMName: ADDR_MODE_IMP, Op: cpu.TAY, AddrMode: cpu.IMP, Cycles: 2},
		{OpName: OPCODE_LDA, AMName: ADDR_MODE_IMM, Op: cpu.LDA, AddrMode: cpu.IMM, Cycles: 2},
		{OpName: OPCODE_TAX, AMName: ADDR_MODE_IMP, Op: cpu.TAX, AddrMode: cpu.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 2},
		{OpName: OPCODE_LDY, AMName: ADDR_MODE_ABS, Op: cpu.LDY, AddrMode: cpu.ABS, Cycles: 4},
		{OpName: OPCODE_LDA, AMName: ADDR_MODE_ABS, Op: cpu.LDA, AddrMode: cpu.ABS, Cycles: 4},
		{OpName: OPCODE_LDX, AMName: ADDR_MODE_ABS, Op: cpu.LDX, AddrMode: cpu.ABS, Cycles: 4},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 4},

		{OpName: OPCODE_BCS, AMName: ADDR_MODE_REL, Op: cpu.BCS, AddrMode: cpu.REL, Cycles: 2},
		{OpName: OPCODE_LDA, AMName: ADDR_MODE_IZY, Op: cpu.LDA, AddrMode: cpu.IZY, Cycles: 5},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 5},
		{OpName: OPCODE_LDY, AMName: ADDR_MODE_ZPX, Op: cpu.LDY, AddrMode: cpu.ZPX, Cycles: 4},
		{OpName: OPCODE_LDA, AMName: ADDR_MODE_ZPX, Op: cpu.LDA, AddrMode: cpu.ZPX, Cycles: 4},
		{OpName: OPCODE_LDX, AMName: ADDR_MODE_ZPY, Op: cpu.LDX, AddrMode: cpu.ZPY, Cycles: 4},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 4},
		{OpName: OPCODE_CLV, AMName: ADDR_MODE_IMP, Op: cpu.CLV, AddrMode: cpu.IMP, Cycles: 2},
		{OpName: OPCODE_LDA, AMName: ADDR_MODE_ABY, Op: cpu.LDA, AddrMode: cpu.ABY, Cycles: 4},
		{OpName: OPCODE_TSX, AMName: ADDR_MODE_IMP, Op: cpu.TSX, AddrMode: cpu.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 4},
		{OpName: OPCODE_LDY, AMName: ADDR_MODE_ABX, Op: cpu.LDY, AddrMode: cpu.ABX, Cycles: 4},
		{OpName: OPCODE_LDA, AMName: ADDR_MODE_ABX, Op: cpu.LDA, AddrMode: cpu.ABX, Cycles: 4},
		{OpName: OPCODE_LDX, AMName: ADDR_MODE_ABY, Op: cpu.LDX, AddrMode: cpu.ABY, Cycles: 4},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 4},

		{OpName: OPCODE_CPY, AMName: ADDR_MODE_IMM, Op: cpu.CPY, AddrMode: cpu.IMM, Cycles: 2},
		{OpName: OPCODE_CMP, AMName: ADDR_MODE_IZX, Op: cpu.CMP, AddrMode: cpu.IZX, Cycles: 6},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.NOP, AddrMode: cpu.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 8},
		{OpName: OPCODE_CPY, AMName: ADDR_MODE_ZP0, Op: cpu.CPY, AddrMode: cpu.ZP0, Cycles: 3},
		{OpName: OPCODE_CMP, AMName: ADDR_MODE_ZP0, Op: cpu.CMP, AddrMode: cpu.ZP0, Cycles: 3},
		{OpName: OPCODE_DEC, AMName: ADDR_MODE_ZP0, Op: cpu.DEC, AddrMode: cpu.ZP0, Cycles: 5},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 5},
		{OpName: OPCODE_INY, AMName: ADDR_MODE_IMP, Op: cpu.INY, AddrMode: cpu.IMP, Cycles: 2},
		{OpName: OPCODE_CMP, AMName: ADDR_MODE_IMM, Op: cpu.CMP, AddrMode: cpu.IMM, Cycles: 2},
		{OpName: OPCODE_DEX, AMName: ADDR_MODE_IMP, Op: cpu.DEX, AddrMode: cpu.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 2},
		{OpName: OPCODE_CPY, AMName: ADDR_MODE_ABS, Op: cpu.CPY, AddrMode: cpu.ABS, Cycles: 4},
		{OpName: OPCODE_CMP, AMName: ADDR_MODE_ABS, Op: cpu.CMP, AddrMode: cpu.ABS, Cycles: 4},
		{OpName: OPCODE_DEC, AMName: ADDR_MODE_ABS, Op: cpu.DEC, AddrMode: cpu.ABS, Cycles: 6},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 6},

		{OpName: OPCODE_BNE, AMName: ADDR_MODE_REL, Op: cpu.BNE, AddrMode: cpu.REL, Cycles: 2},
		{OpName: OPCODE_CMP, AMName: ADDR_MODE_IZY, Op: cpu.CMP, AddrMode: cpu.IZY, Cycles: 5},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 8},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.NOP, AddrMode: cpu.IMP, Cycles: 4},
		{OpName: OPCODE_CMP, AMName: ADDR_MODE_ZPX, Op: cpu.CMP, AddrMode: cpu.ZPX, Cycles: 4},
		{OpName: OPCODE_DEC, AMName: ADDR_MODE_ZPX, Op: cpu.DEC, AddrMode: cpu.ZPX, Cycles: 6},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 6},
		{OpName: OPCODE_CLD, AMName: ADDR_MODE_IMP, Op: cpu.CLD, AddrMode: cpu.IMP, Cycles: 2},
		{OpName: OPCODE_CMP, AMName: ADDR_MODE_ABY, Op: cpu.CMP, AddrMode: cpu.ABY, Cycles: 4},
		{OpName: OPCODE_NOP, AMName: ADDR_MODE_IMP, Op: cpu.NOP, AddrMode: cpu.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 7},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.NOP, AddrMode: cpu.IMP, Cycles: 4},
		{OpName: OPCODE_CMP, AMName: ADDR_MODE_ABX, Op: cpu.CMP, AddrMode: cpu.ABX, Cycles: 4},
		{OpName: OPCODE_DEC, AMName: ADDR_MODE_ABX, Op: cpu.DEC, AddrMode: cpu.ABX, Cycles: 7},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 7},

		{OpName: OPCODE_CPX, AMName: ADDR_MODE_IMM, Op: cpu.CPX, AddrMode: cpu.IMM, Cycles: 2},
		{OpName: OPCODE_SBC, AMName: ADDR_MODE_IZX, Op: cpu.SBC, AddrMode: cpu.IZX, Cycles: 6},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.NOP, AddrMode: cpu.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 8},
		{OpName: OPCODE_CPX, AMName: ADDR_MODE_ZP0, Op: cpu.CPX, AddrMode: cpu.ZP0, Cycles: 3},
		{OpName: OPCODE_SBC, AMName: ADDR_MODE_ZP0, Op: cpu.SBC, AddrMode: cpu.ZP0, Cycles: 3},
		{OpName: OPCODE_INC, AMName: ADDR_MODE_ZP0, Op: cpu.INC, AddrMode: cpu.ZP0, Cycles: 5},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 5},
		{OpName: OPCODE_INX, AMName: ADDR_MODE_IMP, Op: cpu.INX, AddrMode: cpu.IMP, Cycles: 2},
		{OpName: OPCODE_SBC, AMName: ADDR_MODE_IMM, Op: cpu.SBC, AddrMode: cpu.IMM, Cycles: 2},
		{OpName: OPCODE_NOP, AMName: ADDR_MODE_IMP, Op: cpu.NOP, AddrMode: cpu.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.SBC, AddrMode: cpu.IMP, Cycles: 2},
		{OpName: OPCODE_CPX, AMName: ADDR_MODE_ABS, Op: cpu.CPX, AddrMode: cpu.ABS, Cycles: 4},
		{OpName: OPCODE_SBC, AMName: ADDR_MODE_ABS, Op: cpu.SBC, AddrMode: cpu.ABS, Cycles: 4},
		{OpName: OPCODE_INC, AMName: ADDR_MODE_ABS, Op: cpu.INC, AddrMode: cpu.ABS, Cycles: 6},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 6},

		{OpName: OPCODE_BEQ, AMName: ADDR_MODE_REL, Op: cpu.BEQ, AddrMode: cpu.REL, Cycles: 2},
		{OpName: OPCODE_SBC, AMName: ADDR_MODE_IZY, Op: cpu.SBC, AddrMode: cpu.IZY, Cycles: 5},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 8},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.NOP, AddrMode: cpu.IMP, Cycles: 4},
		{OpName: OPCODE_SBC, AMName: ADDR_MODE_ZPX, Op: cpu.SBC, AddrMode: cpu.ZPX, Cycles: 4},
		{OpName: OPCODE_INC, AMName: ADDR_MODE_ZPX, Op: cpu.INC, AddrMode: cpu.ZPX, Cycles: 6},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 6},
		{OpName: OPCODE_SED, AMName: ADDR_MODE_IMP, Op: cpu.SED, AddrMode: cpu.IMP, Cycles: 2},
		{OpName: OPCODE_SBC, AMName: ADDR_MODE_ABY, Op: cpu.SBC, AddrMode: cpu.ABY, Cycles: 4},
		{OpName: OPCODE_NOP, AMName: ADDR_MODE_IMP, Op: cpu.NOP, AddrMode: cpu.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 7},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.NOP, AddrMode: cpu.IMP, Cycles: 4},
		{OpName: OPCODE_SBC, AMName: ADDR_MODE_ABX, Op: cpu.SBC, AddrMode: cpu.ABX, Cycles: 4},
		{OpName: OPCODE_INC, AMName: ADDR_MODE_ABX, Op: cpu.INC, AddrMode: cpu.ABX, Cycles: 7},
		{OpName: OPCODE_UNK, AMName: ADDR_MODE_IMP, Op: cpu.ILL, AddrMode: cpu.IMP, Cycles: 7},
	}
}
