package cpu

// todo change names to byte constants
type Instruction struct {
	OpName       byte
	AddrModeName byte
	AddressMode  func() uint8
	Operation    func() uint8
	Cycles       uint8
}

func newLookupFor(olc6502 *Olc6502) []Instruction {
	return []Instruction{
		{OpName: OPCODE_BRK, AddrModeName: ADDR_MODE_IMM, Operation: olc6502.BRK, AddressMode: olc6502.IMM, Cycles: 7},
		{OpName: OPCODE_ORA, AddrModeName: ADDR_MODE_IZX, Operation: olc6502.ORA, AddressMode: olc6502.IZX, Cycles: 6},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 8},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.NOP, AddressMode: olc6502.IMP, Cycles: 3},
		{OpName: OPCODE_ORA, AddrModeName: ADDR_MODE_ZP0, Operation: olc6502.ORA, AddressMode: olc6502.ZP0, Cycles: 3},
		{OpName: OPCODE_ASL, AddrModeName: ADDR_MODE_ZP0, Operation: olc6502.ASL, AddressMode: olc6502.ZP0, Cycles: 5},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 5},
		{OpName: OPCODE_PHP, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.PHP, AddressMode: olc6502.IMP, Cycles: 3},
		{OpName: OPCODE_ORA, AddrModeName: ADDR_MODE_IMM, Operation: olc6502.ORA, AddressMode: olc6502.IMM, Cycles: 2},
		{OpName: OPCODE_ASL, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ASL, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.NOP, AddressMode: olc6502.IMP, Cycles: 4},
		{OpName: OPCODE_ORA, AddrModeName: ADDR_MODE_ABS, Operation: olc6502.ORA, AddressMode: olc6502.ABS, Cycles: 4},
		{OpName: OPCODE_ASL, AddrModeName: ADDR_MODE_ABS, Operation: olc6502.ASL, AddressMode: olc6502.ABS, Cycles: 6},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 6},

		{OpName: OPCODE_BPL, AddrModeName: ADDR_MODE_REL, Operation: olc6502.BPL, AddressMode: olc6502.REL, Cycles: 2},
		{OpName: OPCODE_ORA, AddrModeName: ADDR_MODE_IZY, Operation: olc6502.ORA, AddressMode: olc6502.IZY, Cycles: 5},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 8},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.NOP, AddressMode: olc6502.IMP, Cycles: 4},
		{OpName: OPCODE_ORA, AddrModeName: ADDR_MODE_ZPX, Operation: olc6502.ORA, AddressMode: olc6502.ZPX, Cycles: 4},
		{OpName: OPCODE_ASL, AddrModeName: ADDR_MODE_ZPX, Operation: olc6502.ASL, AddressMode: olc6502.ZPX, Cycles: 6},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 6},
		{OpName: OPCODE_CLC, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.CLC, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: OPCODE_ORA, AddrModeName: ADDR_MODE_ABY, Operation: olc6502.ORA, AddressMode: olc6502.ABY, Cycles: 4},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.NOP, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 7},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.NOP, AddressMode: olc6502.IMP, Cycles: 4},
		{OpName: OPCODE_ORA, AddrModeName: ADDR_MODE_ABX, Operation: olc6502.ORA, AddressMode: olc6502.ABX, Cycles: 4},
		{OpName: OPCODE_ASL, AddrModeName: ADDR_MODE_ABX, Operation: olc6502.ASL, AddressMode: olc6502.ABX, Cycles: 7},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 7},

		{OpName: OPCODE_JSR, AddrModeName: ADDR_MODE_ABS, Operation: olc6502.JSR, AddressMode: olc6502.ABS, Cycles: 6},
		{OpName: OPCODE_AND, AddrModeName: ADDR_MODE_IZX, Operation: olc6502.AND, AddressMode: olc6502.IZX, Cycles: 6},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 8},
		{OpName: OPCODE_BIT, AddrModeName: ADDR_MODE_ZP0, Operation: olc6502.BIT, AddressMode: olc6502.ZP0, Cycles: 3},
		{OpName: OPCODE_AND, AddrModeName: ADDR_MODE_ZP0, Operation: olc6502.AND, AddressMode: olc6502.ZP0, Cycles: 3},
		{OpName: OPCODE_ROL, AddrModeName: ADDR_MODE_ZP0, Operation: olc6502.ROL, AddressMode: olc6502.ZP0, Cycles: 5},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 5},
		{OpName: OPCODE_PLP, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.PLP, AddressMode: olc6502.IMP, Cycles: 4},
		{OpName: OPCODE_AND, AddrModeName: ADDR_MODE_IMM, Operation: olc6502.AND, AddressMode: olc6502.IMM, Cycles: 2},
		{OpName: OPCODE_ROL, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ROL, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: OPCODE_BIT, AddrModeName: ADDR_MODE_ABS, Operation: olc6502.BIT, AddressMode: olc6502.ABS, Cycles: 4},
		{OpName: OPCODE_AND, AddrModeName: ADDR_MODE_ABS, Operation: olc6502.AND, AddressMode: olc6502.ABS, Cycles: 4},
		{OpName: OPCODE_ROL, AddrModeName: ADDR_MODE_ABS, Operation: olc6502.ROL, AddressMode: olc6502.ABS, Cycles: 6},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 6},

		{OpName: OPCODE_BMI, AddrModeName: ADDR_MODE_REL, Operation: olc6502.BMI, AddressMode: olc6502.REL, Cycles: 2},
		{OpName: OPCODE_AND, AddrModeName: ADDR_MODE_IZY, Operation: olc6502.AND, AddressMode: olc6502.IZY, Cycles: 5},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 8},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.NOP, AddressMode: olc6502.IMP, Cycles: 4},
		{OpName: OPCODE_AND, AddrModeName: ADDR_MODE_ZPX, Operation: olc6502.AND, AddressMode: olc6502.ZPX, Cycles: 4},
		{OpName: OPCODE_ROL, AddrModeName: ADDR_MODE_ZPX, Operation: olc6502.ROL, AddressMode: olc6502.ZPX, Cycles: 6},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 6},
		{OpName: OPCODE_SEC, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.SEC, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: OPCODE_AND, AddrModeName: ADDR_MODE_ABY, Operation: olc6502.AND, AddressMode: olc6502.ABY, Cycles: 4},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.NOP, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 7},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.NOP, AddressMode: olc6502.IMP, Cycles: 4},
		{OpName: OPCODE_AND, AddrModeName: ADDR_MODE_ABX, Operation: olc6502.AND, AddressMode: olc6502.ABX, Cycles: 4},
		{OpName: OPCODE_ROL, AddrModeName: ADDR_MODE_ABX, Operation: olc6502.ROL, AddressMode: olc6502.ABX, Cycles: 7},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 7},

		{OpName: OPCODE_RTI, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.RTI, AddressMode: olc6502.IMP, Cycles: 6},
		{OpName: OPCODE_EOR, AddrModeName: ADDR_MODE_IZX, Operation: olc6502.EOR, AddressMode: olc6502.IZX, Cycles: 6},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 8},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.NOP, AddressMode: olc6502.IMP, Cycles: 3},
		{OpName: OPCODE_EOR, AddrModeName: ADDR_MODE_ZP0, Operation: olc6502.EOR, AddressMode: olc6502.ZP0, Cycles: 3},
		{OpName: OPCODE_LSR, AddrModeName: ADDR_MODE_ZP0, Operation: olc6502.LSR, AddressMode: olc6502.ZP0, Cycles: 5},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 5},
		{OpName: OPCODE_PHA, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.PHA, AddressMode: olc6502.IMP, Cycles: 3},
		{OpName: OPCODE_EOR, AddrModeName: ADDR_MODE_IMM, Operation: olc6502.EOR, AddressMode: olc6502.IMM, Cycles: 2},
		{OpName: OPCODE_LSR, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.LSR, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: OPCODE_JMP, AddrModeName: ADDR_MODE_ABS, Operation: olc6502.JMP, AddressMode: olc6502.ABS, Cycles: 3},
		{OpName: OPCODE_EOR, AddrModeName: ADDR_MODE_ABS, Operation: olc6502.EOR, AddressMode: olc6502.ABS, Cycles: 4},
		{OpName: OPCODE_LSR, AddrModeName: ADDR_MODE_ABS, Operation: olc6502.LSR, AddressMode: olc6502.ABS, Cycles: 6},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 6},

		{OpName: OPCODE_BVC, AddrModeName: ADDR_MODE_REL, Operation: olc6502.BVC, AddressMode: olc6502.REL, Cycles: 2},
		{OpName: OPCODE_EOR, AddrModeName: ADDR_MODE_IZY, Operation: olc6502.EOR, AddressMode: olc6502.IZY, Cycles: 5},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 8},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.NOP, AddressMode: olc6502.IMP, Cycles: 4},
		{OpName: OPCODE_EOR, AddrModeName: ADDR_MODE_ZPX, Operation: olc6502.EOR, AddressMode: olc6502.ZPX, Cycles: 4},
		{OpName: OPCODE_LSR, AddrModeName: ADDR_MODE_ZPX, Operation: olc6502.LSR, AddressMode: olc6502.ZPX, Cycles: 6},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 6},
		{OpName: OPCODE_CLI, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.CLI, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: OPCODE_EOR, AddrModeName: ADDR_MODE_ABY, Operation: olc6502.EOR, AddressMode: olc6502.ABY, Cycles: 4},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.NOP, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 7},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.NOP, AddressMode: olc6502.IMP, Cycles: 4},
		{OpName: OPCODE_EOR, AddrModeName: ADDR_MODE_ABX, Operation: olc6502.EOR, AddressMode: olc6502.ABX, Cycles: 4},
		{OpName: OPCODE_LSR, AddrModeName: ADDR_MODE_ABX, Operation: olc6502.LSR, AddressMode: olc6502.ABX, Cycles: 7},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 7},

		{OpName: OPCODE_RTS, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.RTS, AddressMode: olc6502.IMP, Cycles: 6},
		{OpName: OPCODE_ADC, AddrModeName: ADDR_MODE_IZX, Operation: olc6502.ADC, AddressMode: olc6502.IZX, Cycles: 6},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 8},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.NOP, AddressMode: olc6502.IMP, Cycles: 3},
		{OpName: OPCODE_ADC, AddrModeName: ADDR_MODE_ZP0, Operation: olc6502.ADC, AddressMode: olc6502.ZP0, Cycles: 3},
		{OpName: OPCODE_ROR, AddrModeName: ADDR_MODE_ZP0, Operation: olc6502.ROR, AddressMode: olc6502.ZP0, Cycles: 5},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 5},
		{OpName: OPCODE_PLA, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.PLA, AddressMode: olc6502.IMP, Cycles: 4},
		{OpName: OPCODE_ADC, AddrModeName: ADDR_MODE_IMM, Operation: olc6502.ADC, AddressMode: olc6502.IMM, Cycles: 2},
		{OpName: OPCODE_ROR, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ROR, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: OPCODE_JMP, AddrModeName: ADDR_MODE_IND, Operation: olc6502.JMP, AddressMode: olc6502.IND, Cycles: 5},
		{OpName: OPCODE_ADC, AddrModeName: ADDR_MODE_ABS, Operation: olc6502.ADC, AddressMode: olc6502.ABS, Cycles: 4},
		{OpName: OPCODE_ROR, AddrModeName: ADDR_MODE_ABS, Operation: olc6502.ROR, AddressMode: olc6502.ABS, Cycles: 6},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 6},

		{OpName: OPCODE_BVS, AddrModeName: ADDR_MODE_REL, Operation: olc6502.BVS, AddressMode: olc6502.REL, Cycles: 2},
		{OpName: OPCODE_ADC, AddrModeName: ADDR_MODE_IZY, Operation: olc6502.ADC, AddressMode: olc6502.IZY, Cycles: 5},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 8},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.NOP, AddressMode: olc6502.IMP, Cycles: 4},
		{OpName: OPCODE_ADC, AddrModeName: ADDR_MODE_ZPX, Operation: olc6502.ADC, AddressMode: olc6502.ZPX, Cycles: 4},
		{OpName: OPCODE_ROR, AddrModeName: ADDR_MODE_ZPX, Operation: olc6502.ROR, AddressMode: olc6502.ZPX, Cycles: 6},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 6},
		{OpName: OPCODE_SEI, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.SEI, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: OPCODE_ADC, AddrModeName: ADDR_MODE_ABY, Operation: olc6502.ADC, AddressMode: olc6502.ABY, Cycles: 4},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.NOP, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 7},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.NOP, AddressMode: olc6502.IMP, Cycles: 4},
		{OpName: OPCODE_ADC, AddrModeName: ADDR_MODE_ABX, Operation: olc6502.ADC, AddressMode: olc6502.ABX, Cycles: 4},
		{OpName: OPCODE_ROR, AddrModeName: ADDR_MODE_ABX, Operation: olc6502.ROR, AddressMode: olc6502.ABX, Cycles: 7},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 7},

		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.NOP, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: OPCODE_STA, AddrModeName: ADDR_MODE_IZX, Operation: olc6502.STA, AddressMode: olc6502.IZX, Cycles: 6},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.NOP, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 6},
		{OpName: OPCODE_STY, AddrModeName: ADDR_MODE_ZP0, Operation: olc6502.STY, AddressMode: olc6502.ZP0, Cycles: 3},
		{OpName: OPCODE_STA, AddrModeName: ADDR_MODE_ZP0, Operation: olc6502.STA, AddressMode: olc6502.ZP0, Cycles: 3},
		{OpName: OPCODE_STX, AddrModeName: ADDR_MODE_ZP0, Operation: olc6502.STX, AddressMode: olc6502.ZP0, Cycles: 3},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 3},
		{OpName: OPCODE_DEY, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.DEY, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.NOP, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: OPCODE_TXA, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.TXA, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: OPCODE_STY, AddrModeName: ADDR_MODE_ABS, Operation: olc6502.STY, AddressMode: olc6502.ABS, Cycles: 4},
		{OpName: OPCODE_STA, AddrModeName: ADDR_MODE_ABS, Operation: olc6502.STA, AddressMode: olc6502.ABS, Cycles: 4},
		{OpName: OPCODE_STX, AddrModeName: ADDR_MODE_ABS, Operation: olc6502.STX, AddressMode: olc6502.ABS, Cycles: 4},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 4},

		{OpName: OPCODE_BCC, AddrModeName: ADDR_MODE_REL, Operation: olc6502.BCC, AddressMode: olc6502.REL, Cycles: 2},
		{OpName: OPCODE_STA, AddrModeName: ADDR_MODE_IZY, Operation: olc6502.STA, AddressMode: olc6502.IZY, Cycles: 6},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 6},
		{OpName: OPCODE_STY, AddrModeName: ADDR_MODE_ZPX, Operation: olc6502.STY, AddressMode: olc6502.ZPX, Cycles: 4},
		{OpName: OPCODE_STA, AddrModeName: ADDR_MODE_ZPX, Operation: olc6502.STA, AddressMode: olc6502.ZPX, Cycles: 4},
		{OpName: OPCODE_STX, AddrModeName: ADDR_MODE_ZPY, Operation: olc6502.STX, AddressMode: olc6502.ZPY, Cycles: 4},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 4},
		{OpName: OPCODE_TYA, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.TYA, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: OPCODE_STA, AddrModeName: ADDR_MODE_ABY, Operation: olc6502.STA, AddressMode: olc6502.ABY, Cycles: 5},
		{OpName: OPCODE_TXS, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.TXS, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 5},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.NOP, AddressMode: olc6502.IMP, Cycles: 5},
		{OpName: OPCODE_STA, AddrModeName: ADDR_MODE_ABX, Operation: olc6502.STA, AddressMode: olc6502.ABX, Cycles: 5},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 5},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 5},

		{OpName: OPCODE_LDY, AddrModeName: ADDR_MODE_IMM, Operation: olc6502.LDY, AddressMode: olc6502.IMM, Cycles: 2},
		{OpName: OPCODE_LDA, AddrModeName: ADDR_MODE_IZX, Operation: olc6502.LDA, AddressMode: olc6502.IZX, Cycles: 6},
		{OpName: OPCODE_LDX, AddrModeName: ADDR_MODE_IMM, Operation: olc6502.LDX, AddressMode: olc6502.IMM, Cycles: 2},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 6},
		{OpName: OPCODE_LDY, AddrModeName: ADDR_MODE_ZP0, Operation: olc6502.LDY, AddressMode: olc6502.ZP0, Cycles: 3},
		{OpName: OPCODE_LDA, AddrModeName: ADDR_MODE_ZP0, Operation: olc6502.LDA, AddressMode: olc6502.ZP0, Cycles: 3},
		{OpName: OPCODE_LDX, AddrModeName: ADDR_MODE_ZP0, Operation: olc6502.LDX, AddressMode: olc6502.ZP0, Cycles: 3},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 3},
		{OpName: OPCODE_TAY, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.TAY, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: OPCODE_LDA, AddrModeName: ADDR_MODE_IMM, Operation: olc6502.LDA, AddressMode: olc6502.IMM, Cycles: 2},
		{OpName: OPCODE_TAX, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.TAX, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: OPCODE_LDY, AddrModeName: ADDR_MODE_ABS, Operation: olc6502.LDY, AddressMode: olc6502.ABS, Cycles: 4},
		{OpName: OPCODE_LDA, AddrModeName: ADDR_MODE_ABS, Operation: olc6502.LDA, AddressMode: olc6502.ABS, Cycles: 4},
		{OpName: OPCODE_LDX, AddrModeName: ADDR_MODE_ABS, Operation: olc6502.LDX, AddressMode: olc6502.ABS, Cycles: 4},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 4},

		{OpName: OPCODE_BCS, AddrModeName: ADDR_MODE_REL, Operation: olc6502.BCS, AddressMode: olc6502.REL, Cycles: 2},
		{OpName: OPCODE_LDA, AddrModeName: ADDR_MODE_IZY, Operation: olc6502.LDA, AddressMode: olc6502.IZY, Cycles: 5},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 5},
		{OpName: OPCODE_LDY, AddrModeName: ADDR_MODE_ZPX, Operation: olc6502.LDY, AddressMode: olc6502.ZPX, Cycles: 4},
		{OpName: OPCODE_LDA, AddrModeName: ADDR_MODE_ZPX, Operation: olc6502.LDA, AddressMode: olc6502.ZPX, Cycles: 4},
		{OpName: OPCODE_LDX, AddrModeName: ADDR_MODE_ZPY, Operation: olc6502.LDX, AddressMode: olc6502.ZPY, Cycles: 4},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 4},
		{OpName: OPCODE_CLV, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.CLV, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: OPCODE_LDA, AddrModeName: ADDR_MODE_ABY, Operation: olc6502.LDA, AddressMode: olc6502.ABY, Cycles: 4},
		{OpName: OPCODE_TSX, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.TSX, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 4},
		{OpName: OPCODE_LDY, AddrModeName: ADDR_MODE_ABX, Operation: olc6502.LDY, AddressMode: olc6502.ABX, Cycles: 4},
		{OpName: OPCODE_LDA, AddrModeName: ADDR_MODE_ABX, Operation: olc6502.LDA, AddressMode: olc6502.ABX, Cycles: 4},
		{OpName: OPCODE_LDX, AddrModeName: ADDR_MODE_ABY, Operation: olc6502.LDX, AddressMode: olc6502.ABY, Cycles: 4},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 4},

		{OpName: OPCODE_CPY, AddrModeName: ADDR_MODE_IMM, Operation: olc6502.CPY, AddressMode: olc6502.IMM, Cycles: 2},
		{OpName: OPCODE_CMP, AddrModeName: ADDR_MODE_IZX, Operation: olc6502.CMP, AddressMode: olc6502.IZX, Cycles: 6},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.NOP, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 8},
		{OpName: OPCODE_CPY, AddrModeName: ADDR_MODE_ZP0, Operation: olc6502.CPY, AddressMode: olc6502.ZP0, Cycles: 3},
		{OpName: OPCODE_CMP, AddrModeName: ADDR_MODE_ZP0, Operation: olc6502.CMP, AddressMode: olc6502.ZP0, Cycles: 3},
		{OpName: OPCODE_DEC, AddrModeName: ADDR_MODE_ZP0, Operation: olc6502.DEC, AddressMode: olc6502.ZP0, Cycles: 5},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 5},
		{OpName: OPCODE_INY, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.INY, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: OPCODE_CMP, AddrModeName: ADDR_MODE_IMM, Operation: olc6502.CMP, AddressMode: olc6502.IMM, Cycles: 2},
		{OpName: OPCODE_DEX, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.DEX, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: OPCODE_CPY, AddrModeName: ADDR_MODE_ABS, Operation: olc6502.CPY, AddressMode: olc6502.ABS, Cycles: 4},
		{OpName: OPCODE_CMP, AddrModeName: ADDR_MODE_ABS, Operation: olc6502.CMP, AddressMode: olc6502.ABS, Cycles: 4},
		{OpName: OPCODE_DEC, AddrModeName: ADDR_MODE_ABS, Operation: olc6502.DEC, AddressMode: olc6502.ABS, Cycles: 6},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 6},

		{OpName: OPCODE_BNE, AddrModeName: ADDR_MODE_REL, Operation: olc6502.BNE, AddressMode: olc6502.REL, Cycles: 2},
		{OpName: OPCODE_CMP, AddrModeName: ADDR_MODE_IZY, Operation: olc6502.CMP, AddressMode: olc6502.IZY, Cycles: 5},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 8},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.NOP, AddressMode: olc6502.IMP, Cycles: 4},
		{OpName: OPCODE_CMP, AddrModeName: ADDR_MODE_ZPX, Operation: olc6502.CMP, AddressMode: olc6502.ZPX, Cycles: 4},
		{OpName: OPCODE_DEC, AddrModeName: ADDR_MODE_ZPX, Operation: olc6502.DEC, AddressMode: olc6502.ZPX, Cycles: 6},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 6},
		{OpName: OPCODE_CLD, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.CLD, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: OPCODE_CMP, AddrModeName: ADDR_MODE_ABY, Operation: olc6502.CMP, AddressMode: olc6502.ABY, Cycles: 4},
		{OpName: OPCODE_NOP, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.NOP, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 7},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.NOP, AddressMode: olc6502.IMP, Cycles: 4},
		{OpName: OPCODE_CMP, AddrModeName: ADDR_MODE_ABX, Operation: olc6502.CMP, AddressMode: olc6502.ABX, Cycles: 4},
		{OpName: OPCODE_DEC, AddrModeName: ADDR_MODE_ABX, Operation: olc6502.DEC, AddressMode: olc6502.ABX, Cycles: 7},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 7},

		{OpName: OPCODE_CPX, AddrModeName: ADDR_MODE_IMM, Operation: olc6502.CPX, AddressMode: olc6502.IMM, Cycles: 2},
		{OpName: OPCODE_SBC, AddrModeName: ADDR_MODE_IZX, Operation: olc6502.SBC, AddressMode: olc6502.IZX, Cycles: 6},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.NOP, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 8},
		{OpName: OPCODE_CPX, AddrModeName: ADDR_MODE_ZP0, Operation: olc6502.CPX, AddressMode: olc6502.ZP0, Cycles: 3},
		{OpName: OPCODE_SBC, AddrModeName: ADDR_MODE_ZP0, Operation: olc6502.SBC, AddressMode: olc6502.ZP0, Cycles: 3},
		{OpName: OPCODE_INC, AddrModeName: ADDR_MODE_ZP0, Operation: olc6502.INC, AddressMode: olc6502.ZP0, Cycles: 5},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 5},
		{OpName: OPCODE_INX, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.INX, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: OPCODE_SBC, AddrModeName: ADDR_MODE_IMM, Operation: olc6502.SBC, AddressMode: olc6502.IMM, Cycles: 2},
		{OpName: OPCODE_NOP, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.NOP, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.SBC, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: OPCODE_CPX, AddrModeName: ADDR_MODE_ABS, Operation: olc6502.CPX, AddressMode: olc6502.ABS, Cycles: 4},
		{OpName: OPCODE_SBC, AddrModeName: ADDR_MODE_ABS, Operation: olc6502.SBC, AddressMode: olc6502.ABS, Cycles: 4},
		{OpName: OPCODE_INC, AddrModeName: ADDR_MODE_ABS, Operation: olc6502.INC, AddressMode: olc6502.ABS, Cycles: 6},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 6},

		{OpName: OPCODE_BEQ, AddrModeName: ADDR_MODE_REL, Operation: olc6502.BEQ, AddressMode: olc6502.REL, Cycles: 2},
		{OpName: OPCODE_SBC, AddrModeName: ADDR_MODE_IZY, Operation: olc6502.SBC, AddressMode: olc6502.IZY, Cycles: 5},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 8},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.NOP, AddressMode: olc6502.IMP, Cycles: 4},
		{OpName: OPCODE_SBC, AddrModeName: ADDR_MODE_ZPX, Operation: olc6502.SBC, AddressMode: olc6502.ZPX, Cycles: 4},
		{OpName: OPCODE_INC, AddrModeName: ADDR_MODE_ZPX, Operation: olc6502.INC, AddressMode: olc6502.ZPX, Cycles: 6},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 6},
		{OpName: OPCODE_SED, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.SED, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: OPCODE_SBC, AddrModeName: ADDR_MODE_ABY, Operation: olc6502.SBC, AddressMode: olc6502.ABY, Cycles: 4},
		{OpName: OPCODE_NOP, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.NOP, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 7},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.NOP, AddressMode: olc6502.IMP, Cycles: 4},
		{OpName: OPCODE_SBC, AddrModeName: ADDR_MODE_ABX, Operation: olc6502.SBC, AddressMode: olc6502.ABX, Cycles: 4},
		{OpName: OPCODE_INC, AddrModeName: ADDR_MODE_ABX, Operation: olc6502.INC, AddressMode: olc6502.ABX, Cycles: 7},
		{OpName: OPCODE_UNK, AddrModeName: ADDR_MODE_IMP, Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 7},
	}
}
