package cpu

// todo change names to byte constants
type Instruction struct {
	OpName       string
	AddrModeName string
	AddressMode  func() uint8
	Operation    func() uint8
	Cycles       uint8
}

func newLookupFor(olc6502 *Olc6502) []Instruction {
	return []Instruction{
		{OpName: "BRK", AddrModeName: "IMM", Operation: olc6502.BRK, AddressMode: olc6502.IMM, Cycles: 7},
		{OpName: "ORA", AddrModeName: "IZX", Operation: olc6502.ORA, AddressMode: olc6502.IZX, Cycles: 6},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 8},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.NOP, AddressMode: olc6502.IMP, Cycles: 3},
		{OpName: "ORA", AddrModeName: "ZP0", Operation: olc6502.ORA, AddressMode: olc6502.ZP0, Cycles: 3},
		{OpName: "ASL", AddrModeName: "ZP0", Operation: olc6502.ASL, AddressMode: olc6502.ZP0, Cycles: 5},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 5},
		{OpName: "PHP", AddrModeName: "IMP", Operation: olc6502.PHP, AddressMode: olc6502.IMP, Cycles: 3},
		{OpName: "ORA", AddrModeName: "IMM", Operation: olc6502.ORA, AddressMode: olc6502.IMM, Cycles: 2},
		{OpName: "ASL", AddrModeName: "IMP", Operation: olc6502.ASL, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.NOP, AddressMode: olc6502.IMP, Cycles: 4},
		{OpName: "ORA", AddrModeName: "ABS", Operation: olc6502.ORA, AddressMode: olc6502.ABS, Cycles: 4},
		{OpName: "ASL", AddrModeName: "ABS", Operation: olc6502.ASL, AddressMode: olc6502.ABS, Cycles: 6},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 6},

		{OpName: "BPL", AddrModeName: "REL", Operation: olc6502.BPL, AddressMode: olc6502.REL, Cycles: 2},
		{OpName: "ORA", AddrModeName: "IZY", Operation: olc6502.ORA, AddressMode: olc6502.IZY, Cycles: 5},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 8},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.NOP, AddressMode: olc6502.IMP, Cycles: 4},
		{OpName: "ORA", AddrModeName: "ZPX", Operation: olc6502.ORA, AddressMode: olc6502.ZPX, Cycles: 4},
		{OpName: "ASL", AddrModeName: "ZPX", Operation: olc6502.ASL, AddressMode: olc6502.ZPX, Cycles: 6},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 6},
		{OpName: "CLC", AddrModeName: "IMP", Operation: olc6502.CLC, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: "ORA", AddrModeName: "ABY", Operation: olc6502.ORA, AddressMode: olc6502.ABY, Cycles: 4},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.NOP, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 7},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.NOP, AddressMode: olc6502.IMP, Cycles: 4},
		{OpName: "ORA", AddrModeName: "ABX", Operation: olc6502.ORA, AddressMode: olc6502.ABX, Cycles: 4},
		{OpName: "ASL", AddrModeName: "ABX", Operation: olc6502.ASL, AddressMode: olc6502.ABX, Cycles: 7},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 7},

		{OpName: "JSR", AddrModeName: "ABS", Operation: olc6502.JSR, AddressMode: olc6502.ABS, Cycles: 6},
		{OpName: "AND", AddrModeName: "IZX", Operation: olc6502.AND, AddressMode: olc6502.IZX, Cycles: 6},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 8},
		{OpName: "BIT", AddrModeName: "ZP0", Operation: olc6502.BIT, AddressMode: olc6502.ZP0, Cycles: 3},
		{OpName: "AND", AddrModeName: "ZP0", Operation: olc6502.AND, AddressMode: olc6502.ZP0, Cycles: 3},
		{OpName: "ROL", AddrModeName: "ZP0", Operation: olc6502.ROL, AddressMode: olc6502.ZP0, Cycles: 5},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 5},
		{OpName: "PLP", AddrModeName: "IMP", Operation: olc6502.PLP, AddressMode: olc6502.IMP, Cycles: 4},
		{OpName: "AND", AddrModeName: "IMM", Operation: olc6502.AND, AddressMode: olc6502.IMM, Cycles: 2},
		{OpName: "ROL", AddrModeName: "IMP", Operation: olc6502.ROL, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: "BIT", AddrModeName: "ABS", Operation: olc6502.BIT, AddressMode: olc6502.ABS, Cycles: 4},
		{OpName: "AND", AddrModeName: "ABS", Operation: olc6502.AND, AddressMode: olc6502.ABS, Cycles: 4},
		{OpName: "ROL", AddrModeName: "ABS", Operation: olc6502.ROL, AddressMode: olc6502.ABS, Cycles: 6},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 6},

		{OpName: "BMI", AddrModeName: "REL", Operation: olc6502.BMI, AddressMode: olc6502.REL, Cycles: 2},
		{OpName: "AND", AddrModeName: "IZY", Operation: olc6502.AND, AddressMode: olc6502.IZY, Cycles: 5},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 8},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.NOP, AddressMode: olc6502.IMP, Cycles: 4},
		{OpName: "AND", AddrModeName: "ZPX", Operation: olc6502.AND, AddressMode: olc6502.ZPX, Cycles: 4},
		{OpName: "ROL", AddrModeName: "ZPX", Operation: olc6502.ROL, AddressMode: olc6502.ZPX, Cycles: 6},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 6},
		{OpName: "SEC", AddrModeName: "IMP", Operation: olc6502.SEC, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: "AND", AddrModeName: "ABY", Operation: olc6502.AND, AddressMode: olc6502.ABY, Cycles: 4},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.NOP, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 7},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.NOP, AddressMode: olc6502.IMP, Cycles: 4},
		{OpName: "AND", AddrModeName: "ABX", Operation: olc6502.AND, AddressMode: olc6502.ABX, Cycles: 4},
		{OpName: "ROL", AddrModeName: "ABX", Operation: olc6502.ROL, AddressMode: olc6502.ABX, Cycles: 7},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 7},

		{OpName: "RTI", AddrModeName: "IMP", Operation: olc6502.RTI, AddressMode: olc6502.IMP, Cycles: 6},
		{OpName: "EOR", AddrModeName: "IZX", Operation: olc6502.EOR, AddressMode: olc6502.IZX, Cycles: 6},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 8},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.NOP, AddressMode: olc6502.IMP, Cycles: 3},
		{OpName: "EOR", AddrModeName: "ZP0", Operation: olc6502.EOR, AddressMode: olc6502.ZP0, Cycles: 3},
		{OpName: "LSR", AddrModeName: "ZP0", Operation: olc6502.LSR, AddressMode: olc6502.ZP0, Cycles: 5},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 5},
		{OpName: "PHA", AddrModeName: "IMP", Operation: olc6502.PHA, AddressMode: olc6502.IMP, Cycles: 3},
		{OpName: "EOR", AddrModeName: "IMM", Operation: olc6502.EOR, AddressMode: olc6502.IMM, Cycles: 2},
		{OpName: "LSR", AddrModeName: "IMP", Operation: olc6502.LSR, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: "JMP", AddrModeName: "ABS", Operation: olc6502.JMP, AddressMode: olc6502.ABS, Cycles: 3},
		{OpName: "EOR", AddrModeName: "ABS", Operation: olc6502.EOR, AddressMode: olc6502.ABS, Cycles: 4},
		{OpName: "LSR", AddrModeName: "ABS", Operation: olc6502.LSR, AddressMode: olc6502.ABS, Cycles: 6},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 6},

		{OpName: "BVC", AddrModeName: "REL", Operation: olc6502.BVC, AddressMode: olc6502.REL, Cycles: 2},
		{OpName: "EOR", AddrModeName: "IZY", Operation: olc6502.EOR, AddressMode: olc6502.IZY, Cycles: 5},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 8},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.NOP, AddressMode: olc6502.IMP, Cycles: 4},
		{OpName: "EOR", AddrModeName: "ZPX", Operation: olc6502.EOR, AddressMode: olc6502.ZPX, Cycles: 4},
		{OpName: "LSR", AddrModeName: "ZPX", Operation: olc6502.LSR, AddressMode: olc6502.ZPX, Cycles: 6},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 6},
		{OpName: "CLI", AddrModeName: "IMP", Operation: olc6502.CLI, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: "EOR", AddrModeName: "ABY", Operation: olc6502.EOR, AddressMode: olc6502.ABY, Cycles: 4},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.NOP, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 7},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.NOP, AddressMode: olc6502.IMP, Cycles: 4},
		{OpName: "EOR", AddrModeName: "ABX", Operation: olc6502.EOR, AddressMode: olc6502.ABX, Cycles: 4},
		{OpName: "LSR", AddrModeName: "ABX", Operation: olc6502.LSR, AddressMode: olc6502.ABX, Cycles: 7},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 7},

		{OpName: "RTS", AddrModeName: "IMP", Operation: olc6502.RTS, AddressMode: olc6502.IMP, Cycles: 6},
		{OpName: "ADC", AddrModeName: "IZX", Operation: olc6502.ADC, AddressMode: olc6502.IZX, Cycles: 6},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 8},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.NOP, AddressMode: olc6502.IMP, Cycles: 3},
		{OpName: "ADC", AddrModeName: "ZP0", Operation: olc6502.ADC, AddressMode: olc6502.ZP0, Cycles: 3},
		{OpName: "ROR", AddrModeName: "ZP0", Operation: olc6502.ROR, AddressMode: olc6502.ZP0, Cycles: 5},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 5},
		{OpName: "PLA", AddrModeName: "IMP", Operation: olc6502.PLA, AddressMode: olc6502.IMP, Cycles: 4},
		{OpName: "ADC", AddrModeName: "IMM", Operation: olc6502.ADC, AddressMode: olc6502.IMM, Cycles: 2},
		{OpName: "ROR", AddrModeName: "IMP", Operation: olc6502.ROR, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: "JMP", AddrModeName: "IND", Operation: olc6502.JMP, AddressMode: olc6502.IND, Cycles: 5},
		{OpName: "ADC", AddrModeName: "ABS", Operation: olc6502.ADC, AddressMode: olc6502.ABS, Cycles: 4},
		{OpName: "ROR", AddrModeName: "ABS", Operation: olc6502.ROR, AddressMode: olc6502.ABS, Cycles: 6},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 6},

		{OpName: "BVS", AddrModeName: "REL", Operation: olc6502.BVS, AddressMode: olc6502.REL, Cycles: 2},
		{OpName: "ADC", AddrModeName: "IZY", Operation: olc6502.ADC, AddressMode: olc6502.IZY, Cycles: 5},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 8},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.NOP, AddressMode: olc6502.IMP, Cycles: 4},
		{OpName: "ADC", AddrModeName: "ZPX", Operation: olc6502.ADC, AddressMode: olc6502.ZPX, Cycles: 4},
		{OpName: "ROR", AddrModeName: "ZPX", Operation: olc6502.ROR, AddressMode: olc6502.ZPX, Cycles: 6},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 6},
		{OpName: "SEI", AddrModeName: "IMP", Operation: olc6502.SEI, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: "ADC", AddrModeName: "ABY", Operation: olc6502.ADC, AddressMode: olc6502.ABY, Cycles: 4},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.NOP, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 7},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.NOP, AddressMode: olc6502.IMP, Cycles: 4},
		{OpName: "ADC", AddrModeName: "ABX", Operation: olc6502.ADC, AddressMode: olc6502.ABX, Cycles: 4},
		{OpName: "ROR", AddrModeName: "ABX", Operation: olc6502.ROR, AddressMode: olc6502.ABX, Cycles: 7},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 7},

		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.NOP, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: "STA", AddrModeName: "IZX", Operation: olc6502.STA, AddressMode: olc6502.IZX, Cycles: 6},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.NOP, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 6},
		{OpName: "STY", AddrModeName: "ZP0", Operation: olc6502.STY, AddressMode: olc6502.ZP0, Cycles: 3},
		{OpName: "STA", AddrModeName: "ZP0", Operation: olc6502.STA, AddressMode: olc6502.ZP0, Cycles: 3},
		{OpName: "STX", AddrModeName: "ZP0", Operation: olc6502.STX, AddressMode: olc6502.ZP0, Cycles: 3},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 3},
		{OpName: "DEY", AddrModeName: "IMP", Operation: olc6502.DEY, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.NOP, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: "TXA", AddrModeName: "IMP", Operation: olc6502.TXA, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: "STY", AddrModeName: "ABS", Operation: olc6502.STY, AddressMode: olc6502.ABS, Cycles: 4},
		{OpName: "STA", AddrModeName: "ABS", Operation: olc6502.STA, AddressMode: olc6502.ABS, Cycles: 4},
		{OpName: "STX", AddrModeName: "ABS", Operation: olc6502.STX, AddressMode: olc6502.ABS, Cycles: 4},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 4},

		{OpName: "BCC", AddrModeName: "REL", Operation: olc6502.BCC, AddressMode: olc6502.REL, Cycles: 2},
		{OpName: "STA", AddrModeName: "IZY", Operation: olc6502.STA, AddressMode: olc6502.IZY, Cycles: 6},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 6},
		{OpName: "STY", AddrModeName: "ZPX", Operation: olc6502.STY, AddressMode: olc6502.ZPX, Cycles: 4},
		{OpName: "STA", AddrModeName: "ZPX", Operation: olc6502.STA, AddressMode: olc6502.ZPX, Cycles: 4},
		{OpName: "STX", AddrModeName: "ZPY", Operation: olc6502.STX, AddressMode: olc6502.ZPY, Cycles: 4},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 4},
		{OpName: "TYA", AddrModeName: "IMP", Operation: olc6502.TYA, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: "STA", AddrModeName: "ABY", Operation: olc6502.STA, AddressMode: olc6502.ABY, Cycles: 5},
		{OpName: "TXS", AddrModeName: "IMP", Operation: olc6502.TXS, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 5},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.NOP, AddressMode: olc6502.IMP, Cycles: 5},
		{OpName: "STA", AddrModeName: "ABX", Operation: olc6502.STA, AddressMode: olc6502.ABX, Cycles: 5},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 5},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 5},

		{OpName: "LDY", AddrModeName: "IMM", Operation: olc6502.LDY, AddressMode: olc6502.IMM, Cycles: 2},
		{OpName: "LDA", AddrModeName: "IZX", Operation: olc6502.LDA, AddressMode: olc6502.IZX, Cycles: 6},
		{OpName: "LDX", AddrModeName: "IMM", Operation: olc6502.LDX, AddressMode: olc6502.IMM, Cycles: 2},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 6},
		{OpName: "LDY", AddrModeName: "ZP0", Operation: olc6502.LDY, AddressMode: olc6502.ZP0, Cycles: 3},
		{OpName: "LDA", AddrModeName: "ZP0", Operation: olc6502.LDA, AddressMode: olc6502.ZP0, Cycles: 3},
		{OpName: "LDX", AddrModeName: "ZP0", Operation: olc6502.LDX, AddressMode: olc6502.ZP0, Cycles: 3},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 3},
		{OpName: "TAY", AddrModeName: "IMP", Operation: olc6502.TAY, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: "LDA", AddrModeName: "IMM", Operation: olc6502.LDA, AddressMode: olc6502.IMM, Cycles: 2},
		{OpName: "TAX", AddrModeName: "IMP", Operation: olc6502.TAX, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: "LDY", AddrModeName: "ABS", Operation: olc6502.LDY, AddressMode: olc6502.ABS, Cycles: 4},
		{OpName: "LDA", AddrModeName: "ABS", Operation: olc6502.LDA, AddressMode: olc6502.ABS, Cycles: 4},
		{OpName: "LDX", AddrModeName: "ABS", Operation: olc6502.LDX, AddressMode: olc6502.ABS, Cycles: 4},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 4},

		{OpName: "BCS", AddrModeName: "REL", Operation: olc6502.BCS, AddressMode: olc6502.REL, Cycles: 2},
		{OpName: "LDA", AddrModeName: "IZY", Operation: olc6502.LDA, AddressMode: olc6502.IZY, Cycles: 5},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 5},
		{OpName: "LDY", AddrModeName: "ZPX", Operation: olc6502.LDY, AddressMode: olc6502.ZPX, Cycles: 4},
		{OpName: "LDA", AddrModeName: "ZPX", Operation: olc6502.LDA, AddressMode: olc6502.ZPX, Cycles: 4},
		{OpName: "LDX", AddrModeName: "ZPY", Operation: olc6502.LDX, AddressMode: olc6502.ZPY, Cycles: 4},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 4},
		{OpName: "CLV", AddrModeName: "IMP", Operation: olc6502.CLV, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: "LDA", AddrModeName: "ABY", Operation: olc6502.LDA, AddressMode: olc6502.ABY, Cycles: 4},
		{OpName: "TSX", AddrModeName: "IMP", Operation: olc6502.TSX, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 4},
		{OpName: "LDY", AddrModeName: "ABX", Operation: olc6502.LDY, AddressMode: olc6502.ABX, Cycles: 4},
		{OpName: "LDA", AddrModeName: "ABX", Operation: olc6502.LDA, AddressMode: olc6502.ABX, Cycles: 4},
		{OpName: "LDX", AddrModeName: "ABY", Operation: olc6502.LDX, AddressMode: olc6502.ABY, Cycles: 4},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 4},

		{OpName: "CPY", AddrModeName: "IMM", Operation: olc6502.CPY, AddressMode: olc6502.IMM, Cycles: 2},
		{OpName: "CMP", AddrModeName: "IZX", Operation: olc6502.CMP, AddressMode: olc6502.IZX, Cycles: 6},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.NOP, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 8},
		{OpName: "CPY", AddrModeName: "ZP0", Operation: olc6502.CPY, AddressMode: olc6502.ZP0, Cycles: 3},
		{OpName: "CMP", AddrModeName: "ZP0", Operation: olc6502.CMP, AddressMode: olc6502.ZP0, Cycles: 3},
		{OpName: "DEC", AddrModeName: "ZP0", Operation: olc6502.DEC, AddressMode: olc6502.ZP0, Cycles: 5},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 5},
		{OpName: "INY", AddrModeName: "IMP", Operation: olc6502.INY, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: "CMP", AddrModeName: "IMM", Operation: olc6502.CMP, AddressMode: olc6502.IMM, Cycles: 2},
		{OpName: "DEX", AddrModeName: "IMP", Operation: olc6502.DEX, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: "CPY", AddrModeName: "ABS", Operation: olc6502.CPY, AddressMode: olc6502.ABS, Cycles: 4},
		{OpName: "CMP", AddrModeName: "ABS", Operation: olc6502.CMP, AddressMode: olc6502.ABS, Cycles: 4},
		{OpName: "DEC", AddrModeName: "ABS", Operation: olc6502.DEC, AddressMode: olc6502.ABS, Cycles: 6},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 6},

		{OpName: "BNE", AddrModeName: "REL", Operation: olc6502.BNE, AddressMode: olc6502.REL, Cycles: 2},
		{OpName: "CMP", AddrModeName: "IZY", Operation: olc6502.CMP, AddressMode: olc6502.IZY, Cycles: 5},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 8},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.NOP, AddressMode: olc6502.IMP, Cycles: 4},
		{OpName: "CMP", AddrModeName: "ZPX", Operation: olc6502.CMP, AddressMode: olc6502.ZPX, Cycles: 4},
		{OpName: "DEC", AddrModeName: "ZPX", Operation: olc6502.DEC, AddressMode: olc6502.ZPX, Cycles: 6},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 6},
		{OpName: "CLD", AddrModeName: "IMP", Operation: olc6502.CLD, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: "CMP", AddrModeName: "ABY", Operation: olc6502.CMP, AddressMode: olc6502.ABY, Cycles: 4},
		{OpName: "NOP", AddrModeName: "IMP", Operation: olc6502.NOP, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 7},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.NOP, AddressMode: olc6502.IMP, Cycles: 4},
		{OpName: "CMP", AddrModeName: "ABX", Operation: olc6502.CMP, AddressMode: olc6502.ABX, Cycles: 4},
		{OpName: "DEC", AddrModeName: "ABX", Operation: olc6502.DEC, AddressMode: olc6502.ABX, Cycles: 7},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 7},

		{OpName: "CPX", AddrModeName: "IMM", Operation: olc6502.CPX, AddressMode: olc6502.IMM, Cycles: 2},
		{OpName: "SBC", AddrModeName: "IZX", Operation: olc6502.SBC, AddressMode: olc6502.IZX, Cycles: 6},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.NOP, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 8},
		{OpName: "CPX", AddrModeName: "ZP0", Operation: olc6502.CPX, AddressMode: olc6502.ZP0, Cycles: 3},
		{OpName: "SBC", AddrModeName: "ZP0", Operation: olc6502.SBC, AddressMode: olc6502.ZP0, Cycles: 3},
		{OpName: "INC", AddrModeName: "ZP0", Operation: olc6502.INC, AddressMode: olc6502.ZP0, Cycles: 5},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 5},
		{OpName: "INX", AddrModeName: "IMP", Operation: olc6502.INX, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: "SBC", AddrModeName: "IMM", Operation: olc6502.SBC, AddressMode: olc6502.IMM, Cycles: 2},
		{OpName: "NOP", AddrModeName: "IMP", Operation: olc6502.NOP, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.SBC, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: "CPX", AddrModeName: "ABS", Operation: olc6502.CPX, AddressMode: olc6502.ABS, Cycles: 4},
		{OpName: "SBC", AddrModeName: "ABS", Operation: olc6502.SBC, AddressMode: olc6502.ABS, Cycles: 4},
		{OpName: "INC", AddrModeName: "ABS", Operation: olc6502.INC, AddressMode: olc6502.ABS, Cycles: 6},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 6},

		{OpName: "BEQ", AddrModeName: "REL", Operation: olc6502.BEQ, AddressMode: olc6502.REL, Cycles: 2},
		{OpName: "SBC", AddrModeName: "IZY", Operation: olc6502.SBC, AddressMode: olc6502.IZY, Cycles: 5},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 8},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.NOP, AddressMode: olc6502.IMP, Cycles: 4},
		{OpName: "SBC", AddrModeName: "ZPX", Operation: olc6502.SBC, AddressMode: olc6502.ZPX, Cycles: 4},
		{OpName: "INC", AddrModeName: "ZPX", Operation: olc6502.INC, AddressMode: olc6502.ZPX, Cycles: 6},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 6},
		{OpName: "SED", AddrModeName: "IMP", Operation: olc6502.SED, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: "SBC", AddrModeName: "ABY", Operation: olc6502.SBC, AddressMode: olc6502.ABY, Cycles: 4},
		{OpName: "NOP", AddrModeName: "IMP", Operation: olc6502.NOP, AddressMode: olc6502.IMP, Cycles: 2},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 7},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.NOP, AddressMode: olc6502.IMP, Cycles: 4},
		{OpName: "SBC", AddrModeName: "ABX", Operation: olc6502.SBC, AddressMode: olc6502.ABX, Cycles: 4},
		{OpName: "INC", AddrModeName: "ABX", Operation: olc6502.INC, AddressMode: olc6502.ABX, Cycles: 7},
		{OpName: "???", AddrModeName: "IMP", Operation: olc6502.ILL, AddressMode: olc6502.IMP, Cycles: 7},
	}
}
